Add support for kopia diff --json
kopia/kopia pull request #767
Opened 2021-01-05 13:51 UTC by eras

This produces a basic JSON version of the textual content provided by the `kopia diff` command; most useful when combined with the use of `jq`.

Activated with a `diff`-specific `--json`-switch, so it does not try to be general in any way and the mapping from the old output to the JSON is pretty much 1:1—so there's maybe some amount of redundancy and it does not try to collect output e.g. per-file or anything. And definitely nothing as all-encompassing as what https://github.com/kopia/kopia/issues/272 aims for.

But it's still probably quite useful for analyzing the changes in the repo.

2021-01-05 15:55 UTC, jkowalski commented
One more thought (and probably more difficult): could this use JSON nesting:

```
{
  "someDir": {
    "someFile": {
      "change": "added",
       "new": {
          "oid": "abc1235"
       },
    },
    "someOtherFile": {
      "changeType": "changed",
       "old": {
          "oid": "abc1234"
       },
       "new": {
          "oid": "abc1235"
       }
    },
   }
}
```

And so on. Many things need to be figured out here w.r.t. the format (perhaps there's an existing one we can use or something close to it)?

2021-01-06 10:39 UTC, eras commented
I figured just going with basically the same text output but as JSON wouldn't be enough ;).

The only "standard" format for representing differences I know of are `diff` and `xdelta`; I'm not aware of format suitable for representing this kind of data.

I'm of the opinion that JSON nesting is not the way to go. In particular, it is more complicated to process with simple tools, even though `jq` is able to do recursion—and it's an advanced topic with `jq`.

Something like a flat

```
{ "entries": [{
    "path/file" : {
      "change": "add"|"remove"|"update",
      "path_type": "directory"|"file"|..,
      "size_delta": 42,
      "update": ["size", "modtime", "modtimestamp"],
      "new": {
        "size": 42,
        "unix": {
          "permissions": "-rwxrwx---",
          "userid": 1001,
          "groupid": 1002,
        },
        "modtime": 1000000001,
        "modtimestamp": "2001-09-09..."
      },
      "old": {
        ...
      },
      "diff": {
        "exit_code": 1,
        "output": "..."
      }}, ...]}
```

might be more consistent, easier to process, and easier to convert to non-hierarchic formats, than the current format.

Of course, at the cost of more code :). The amount of information provided from the `Diff` module to `ComparerOutput` probably needs be increased.

If a hierarchic format is truly desirable then it could be implemented purely in the JSON output module, by building a tree out of the existing data. But it's quite unclear to me if that would be even desirable; the flat format has its benefits and I would like to keep it. Producing hierarchic output mode could be added later, with e.g. an additional switch, if the need for it rises at all. In that format i would just move add and "entries" array to the change object and possible otherwise empty intermediate objects for representing unchanged intermediate directories.

2021-01-10 19:04 UTC, jkowalski requested changes

2021-01-10 19:04 UTC, jkowalski commented on internal/diff/diff.go
> +	OutputJSON = iota
nit - iota can be removed here

2021-01-10 19:04 UTC, jkowalski commented on tests/end_to_end_test/restore_test.go
> +		cmp, err := diff.NewComparer(os.Stderr, diff.OutputText)
Can we add a test for the JSON format?

2021-05-16 22:20 UTC, jkowalski commented
any updates here? since this PR had activity there have been a bunch of changes that caused conflicts.

2021-12-12 16:39 UTC, jkowalski commented
this has been stale for a while, please rebase and open new PR if you intend to pursue this.

2021-12-12 16:39 UTC, closed without merging